#spring.application.name=Backend
spring:
  sql:
    init:
      platform: h2
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./database
    username: backend
    password: backend
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true

logging:
  level:
#    web: trace
#  level:
    org:
      springframework:
        web: debug
        security: trace

#debug: true
